      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: vatsal-shethia
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage

          plugin_achievements: yes
          plugin_achievements_display: compact

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 30

          plugin_followup: yes
          plugin_calendar: yes
